name: Styrelsekvinna
favicon: null
layout_spectrum: 0.5106030663009733
typography_spectrum: 0.07456366927362978
title: Styrelsekvinna
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4757087165489793
  lightness: 0.6332163710612804
  saturation: 0.7648771447129548
  rhythmicContrast: 0.5009794221259654
purpose: []
